# Generated by Django 6.1.1 on 2026-09-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descripion',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
